### ISSUE TITLE
Task 'GitDownloader' (0.3.3) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

### ISSUE THREAD

**Issue by eclipses** [fakhrulhilal/TFSGitDownloader#8]
Hi, 

This morning I noted this warning in a build, please let me know if any action is needed from my side.

"Task 'GitDownloader' (0.3.3) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib"

Thanks
Sergio Castelluccio

**Comment by richardgavel** [comment]
You can't. I saw this Cake, as a warning in one spot and an error in another: ##[error]Task 'Git Repository Downloader' is using legacy execution handler 'Microsoft.VisualStudio.Services.Agent.Worker.PowerShellHandlerData' which is not supported in container execution flow.

The issue is the task is using an older "Azure DevOps" custom extension "executor type" of "Powershell" and needs to update to "Powershell3". 

Similar to https://github.com/cake-build/cake-vso/pull/49

**Comment by fakhrulhilal** [comment]
Do you know how to reproduce the issue? What OS are you using, which powershell version installed in it?

**Comment by richardgavel** [comment]
Using a Windows 2016 based self hosted agent, and technically it's not a powershell error. It's because the Azure DevOps agent simply sees the task definition references the executor type of powershell. In normal builds, it throws a warning but will still run the task. But the agent simply won't run the task when the build is running inside a container (the executor type is not supported when running inside a container).

https://github.com/microsoft/azure-pipelines-agent/blob/90dff0213a33cf484594c30420c0f1aa3085c6f6/src/Agent.Worker/Handlers/LegacyPowerShellHandler.cs#L181
